services:
  - type: web
    name: recipebook-backend
    runtime: node
    buildCommand: npm install -w backend
    startCommand: npm start -w backend
    envVars:
      - key: NODE_ENV
        value: production
